@startuml

entity post {
  *id: bigint(20)
  ---
  profile_id: bigint(20)
  content: text
  status: varchar(50)
  images: json
  created_at: timestamp
  modified_at: timestamp
}

entity post_read_record {
  *id: bigint(20)
  ---
  profile_id: bigint(20)
  post_id: bigint(20)
  created_at: timestamp
}

entity reaction {
  *id: bigint(20)
  ---
  expression: varchar(20)
  parent_id: bigint(20)
  profile_id: bigint(20)
  type: varchar(50)
  created_at: timestamp
  modified_at: timestamp
}

entity comment {
  *id: bigint(20)
  ---
  profile_id: bigint(20)
  post_id: bigint(20)
  comment_id: bigint(20)
  content: text
  created_at: timestamp
  modified_at: timestamp
}

profile ||--o{ post
profile ||--o{ reaction
profile ||--o{ comment
post ||--o{ comment
post ||--o{ reaction
profile ||--o{ post_read_record
post ||--o{ post_read_record
comment ||--o{ comment

@enduml
