@startuml
'https://plantuml.com/class-diagram

class User {
  *id: Long
  +email: String?
  +password: String?
  +status: UserStatus
  +name: String
  ..
  createdAt: Instant
  createdById: Long
  createdByRole: UserRole
  modifiedAt: Instant
  modifiedById: Long
  modifiedByRole: UserRole
}

enum UserStatus {
  ACTIVE
  INACTIVE
  REGULATED
  DORMANT
}

User::status --> UserStatus

@enduml
