@startuml
'https://plantuml.com/class-diagram

class User {
  *id: Long
  +email: String?
  +password: String?
  +status: UserStatus
  +name: String
  +birthDate: Date?
  +gender: Gender
  ..
  createdAt: Instant
  createdById: Long
  createdByRole: UserRole
  modifiedAt: Instant
  modifiedById: Long
  modifiedByRole: UserRole
}

enum UserStatus {
  ACTIVE
  INACTIVE
  REGULATED
  DORMANT
}

enum Gender {
  FEMALE
  MALE
  NONE
}

enum UserRole {
  ADMIN
  USER
}

User::status --> UserStatus
User::gender --> Gender
User::createdByRole --> UserRole
User::modifiedByRole --> UserRole

@enduml
