@startuml

class Comment {
  id: Long
  user_id: Long
  post_id: Long
  comment_id: Long
  content: String
  ..
  createdAt: Instant
  createdById: Long
  createdByRole: UserRole
  modifiedAt: Instant
  modifiedById: Long
  modifiedByRole: UserRole
}

@enduml