@startuml

class Post {
  id: Long
  user_id: Long
  content: String
  status: Status
  images: List<String>
  created_at: LocalDateTime
  modified_at: LocalDateTime
}

class PostReadRecord {
  id: Long
  user_id: Long
  post_id: Long
  created_at: LocalDateTime
}

@enduml