@startuml

class Post {
  id: Long
  user_id: Long
  content: String
  status: Status
  images: List<String>
  ..
  createdAt: Instant
  createdById: Long
  createdByRole: UserRole
  modifiedAt: Instant
  modifiedById: Long
  modifiedByRole: UserRole
}

class PostReadRecord {
  id: Long
  profile_id: Long
  target_profile_id: Long
  lastPostId: Long
  ..
  createdAt: Instant
  createdById: Long
  createdByRole: UserRole
  modifiedAt: Instant
  modifiedById: Long
  modifiedByRole: UserRole
}

@enduml