@startuml

class Reaction {
  id: Long
  expression: Expression
  parent_id: Long
  user_id: Long
  type: Type
  ..
  createdAt: Instant
  createdById: Long
  createdByRole: UserRole
  modifiedAt: Instant
  modifiedById: Long
  modifiedByRole: UserRole
}

enum Expression {
  LIKE
}

enum Type {
  POST
  COMMENT
}

Reaction::expression --> Expression
Reaction::type --> Type

@enduml