@startuml
'https://plantuml.com/class-diagram

@startuml
class Biometrics {
  *id: Long
  +userId: Long
  +height: Float
  +weight: Float
  +age: Int
  +gender: Gender
  +activityLevel: ActivityLevel
  ..
  createdAt: Instant
  createdById: Long
  createdByRole: UserRole
  modifiedAt: Instant
  modifiedById: Long
  modifiedByRole: UserRole
}

enum Gender {
  FEMALE
  MALE
  NONE
}

enum ActivityLevel {
  SEDENTARY,
  LIGHTLY_ACTIVE,
  MODERATELY_ACTIVE,
  ACTIVE,
  VERY_ACTIVE,
}

enum UserRole {
  ADMIN
  USER
}

Biometrics::gender --> Gender
Biometrics::ActivityLevel --> ActivityLevel
Biometrics::createdByRole --> UserRole
Biometrics::modifiedByRole --> UserRole

@enduml
