@startuml
'https://plantuml.com/class-diagram

class DietRecord {
  *id: Long
  +userId: Long
  +foodName: String
  +calories: Float
  +weight: Float
  +photoUrl: String
  +date: Instant
  ..
  createdAt: Instant
  createdById: Long
  createdByRole: UserRole
  modifiedAt: Instant
  modifiedById: Long
  modifiedByRole: UserRole
}

class FoodCategory {
  *id: Long
  +name: String
  ..
  createdAt: Instant
  createdById: Long
  createdByRole: UserRole
  modifiedAt: Instant
  modifiedById: Long
  modifiedByRole: UserRole
}

class Food {
  *id: Long
  +name: String
  +unitCalories: Int
  ..
  createdAt: Instant
  createdById: Long
  createdByRole: UserRole
  modifiedAt: Instant
  modifiedById: Long
  modifiedByRole: UserRole
}


@enduml
