@startuml
'https://plantuml.com/class-diagram

class FitnessGoal {
  *id: Int
  +userId: Int
  +weight: FLOAT
  +dailyExerciseCalories: Int
  +exerciseFrequency: Int
  +exercisePlan: TEXT
  +diet_plan: TEXT
  +deadline: DATE
  ..
  createdAt: Instant
  createdById: Long
  createdByRole: UserRole
  modifiedAt: Instant
  modifiedById: Long
  modifiedByRole: UserRole
}

@enduml
