@startuml
'https://plantuml.com/class-diagram

@startuml
class HealthStatus {
  *id: Long
  +userId: Long
  +height: Float
  +weight: Float
  +age: Int
  +gender: Gender
  ..
  createdAt: Instant
  createdById: Long
  createdByRole: UserRole
  modifiedAt: Instant
  modifiedById: Long
  modifiedByRole: UserRole
}

enum Gender {
  FEMALE
  MALE
  NONE
}

enum UserRole {
  ADMIN
  USER
}

HealthStatus::gender --> Gender
HealthStatus::createdByRole --> UserRole
HealthStatus::modifiedByRole --> UserRole

@enduml
