@startuml
'https://plantuml.com/sequence-diagram

actor 사용자
participant "앱" as app
participant "웹" as web
participant "서버" as server

사용자 -> app : 회원가입 완료 
app -> app : 아이디, 닉네임 정보 입력
app -> web : {"accessToken":"token", "id":"id","nickname":"nickname"}
web -> app : 현재까지의 onboarding json data 전달
app -> web : 사진 binary data 추가 후 전달
web -> web : 나머지 정보 입력
web -> app : 현재까지의 onboarding json data 전달
app -> app : 건강앱 정보 추가
app -> server : onboarding json data 전달
