@startuml
'https://plantuml.com/class-diagram

class Relationship {
  *profileId: Long
  *targetProfileId: Long
  +status: RelationshipStatus
  ..
  createdAt: Instant
  createdById: Long
  createdByRole: UserRole
  modifiedAt: Instant
  modifiedById: Long
  modifiedByRole: UserRole
}

enum RelationshipStatus {
  REQUESTED
  FOLLOWING
  BLOCKING
}

enum UserRole {
  ADMIN
  USER
}

Relationship::status --> RelationshipStatus
Relationship::createdByRole --> UserRole

note right of Relationship::description
  상태 메시지
end note

note right of Relationship::imagePath
  프로필 이미지 경로
end note

@enduml
